"""models

Revision ID: b4261fd4c227
Revises: 
Create Date: 2024-06-29 17:57:10.700684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4261fd4c227'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('close_status', sa.Boolean(), nullable=True, comment='Статус закрытия'),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Время закрытия'),
    sa.Column('task', sa.String(), nullable=True, comment='Представление задания на смену'),
    sa.Column('work_center', sa.String(), nullable=True, comment='Рабочий центр'),
    sa.Column('shift', sa.String(), nullable=True, comment='Смена'),
    sa.Column('crew', sa.String(), nullable=True, comment='Бригада'),
    sa.Column('lot_number', sa.Integer(), nullable=True, comment='Номер партии'),
    sa.Column('lot_date', sa.Date(), nullable=True, comment='Дата партии'),
    sa.Column('name', sa.String(), nullable=True, comment='Номенклатура'),
    sa.Column('codeEKN', sa.String(), nullable=True, comment='кодЕКН'),
    sa.Column('DC_id', sa.String(), nullable=True, comment='идентификатор РЦ '),
    sa.Column('shift_start', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('shift_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('is_aggregated', sa.Boolean(), nullable=True),
    sa.Column('aggregated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
