"""adjust product model

Revision ID: ff18db8e066f
Revises: 525495bfcc64
Create Date: 2024-06-29 16:12:30.586006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff18db8e066f'
down_revision: Union[str, None] = '525495bfcc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('task_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_aggregated', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('aggregated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_foreign_key(None, 'products', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'aggregated_at')
    op.drop_column('products', 'is_aggregated')
    op.drop_column('products', 'task_id')
    # ### end Alembic commands ###
